# Generated by Django 6.0.4 on 2026-05-09 10:47

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ContactMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120)),
                ('email', models.EmailField(max_length=254)),
                ('phone', models.CharField(blank=True, max_length=20, null=True)),
                ('message_type', models.CharField(choices=[('inquiry', 'Inquiry'), ('suggestion', 'Suggestion'), ('technical_issue', 'Technical Issue'), ('other', 'Other')], max_length=30)),
                ('other_type', models.CharField(blank=True, max_length=120, null=True)),
                ('subject', models.CharField(max_length=180)),
                ('message', models.TextField()),
                ('is_read', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
