# Generated by Django 6.0.4 on 2026-05-01 02:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stadium', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='stadium',
            options={'ordering': ['-created_at'], 'verbose_name': 'Stadium', 'verbose_name_plural': 'Stadiums'},
        ),
        migrations.AlterUniqueTogether(
            name='stadium',
            unique_together={('name', 'city')},
        ),
        migrations.CreateModel(
            name='Facility',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('type', models.CharField(max_length=50)),
                ('location', models.CharField(max_length=200)),
                ('x_coordinate', models.FloatField()),
                ('y_coordinate', models.FloatField()),
                ('status', models.CharField(max_length=20)),
                ('stadium', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='facilities', to='stadium.stadium')),
            ],
            options={
                'unique_together': {('stadium', 'name')},
            },
        ),
        migrations.CreateModel(
            name='Gate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('status', models.CharField(choices=[('open', 'Open'), ('closed', 'Closed'), ('maintenance', 'Maintenance')], default='closed', max_length=20)),
                ('stadium', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='gates', to='stadium.stadium')),
            ],
            options={
                'verbose_name': 'Gate',
                'verbose_name_plural': 'Gates',
                'ordering': ['name'],
                'unique_together': {('stadium', 'name')},
            },
        ),
        migrations.CreateModel(
            name='Parking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('location', models.CharField(max_length=255)),
                ('capacity_spots', models.PositiveIntegerField()),
                ('available_spots', models.PositiveIntegerField()),
                ('status', models.CharField(choices=[('available', 'Available'), ('full', 'Full'), ('closed', 'Closed')], default='available', max_length=20)),
                ('stadium', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='parkings', to='stadium.stadium')),
            ],
            options={
                'verbose_name': 'Parking',
                'verbose_name_plural': 'Parkings',
                'ordering': ['name'],
                'unique_together': {('stadium', 'name')},
            },
        ),
    ]
