# Generated by Django 6.0.4 on 2026-05-09 21:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stadium', '0003_alter_facility_options_gate_crowd_percentage_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='gate',
            name='crowd_percentage',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
