# Generated by Django 6.0.4 on 2026-05-06 14:27

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0001_initial'),
        ('match', '0004_alter_match_available_tickets_and_more'),
        ('stadium', '0003_alter_facility_options_gate_crowd_percentage_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='supportmessage',
            name='user',
        ),
        migrations.CreateModel(
            name='GateStatusUpdate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('open', 'Open'), ('closed', 'Closed'), ('crowded', 'Crowded'), ('emergency', 'Emergency')], default='open', max_length=20)),
                ('message', models.TextField(blank=True)),
                ('notify_users', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('alternative_gate', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='alternative_updates', to='stadium.gate')),
                ('gate', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='status_updates', to='stadium.gate')),
                ('match', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='gate_updates', to='match.match')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.DeleteModel(
            name='Notification',
        ),
        migrations.DeleteModel(
            name='SupportMessage',
        ),
    ]
