# Generated by Django 6.0.4 on 2026-05-06 14:34

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0002_remove_supportmessage_user_gatestatusupdate_and_more'),
        ('stadium', '0003_alter_facility_options_gate_crowd_percentage_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='gatestatusupdate',
            options={'ordering': ['-created_at'], 'verbose_name': 'Gate Status Update', 'verbose_name_plural': 'Gate Status Updates'},
        ),
        migrations.AddField(
            model_name='gatestatusupdate',
            name='affected_ticket_count',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='gatestatusupdate',
            name='internal_note',
            field=models.TextField(blank=True, help_text='Private note for organizers only.'),
        ),
        migrations.AddField(
            model_name='gatestatusupdate',
            name='notification_sent',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='gatestatusupdate',
            name='priority',
            field=models.CharField(choices=[('low', 'Low'), ('normal', 'Normal'), ('high', 'High'), ('critical', 'Critical')], default='normal', max_length=20),
        ),
        migrations.AddField(
            model_name='gatestatusupdate',
            name='title',
            field=models.CharField(blank=True, max_length=120),
        ),
        migrations.AlterField(
            model_name='gatestatusupdate',
            name='alternative_gate',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='alternative_status_updates', to='stadium.gate'),
        ),
        migrations.AlterField(
            model_name='gatestatusupdate',
            name='message',
            field=models.TextField(blank=True, help_text='Message shown to organizers and optionally sent to visitors.'),
        ),
        migrations.AlterField(
            model_name='gatestatusupdate',
            name='status',
            field=models.CharField(choices=[('open', 'Open'), ('closed', 'Closed'), ('crowded', 'Crowded'), ('emergency', 'Emergency'), ('maintenance', 'Maintenance')], default='open', max_length=20),
        ),
        migrations.AlterField(
            model_name='gatestatusupdate',
            name='updated_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='gate_status_updates', to=settings.AUTH_USER_MODEL),
        ),
    ]
