# Generated by Django 6.0.4 on 2026-05-04 16:16

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0001_initial'),
        ('match', '0003_match_video_file_alter_match_video_url'),
        ('stadium', '0002_alter_stadium_options_alter_stadium_unique_together_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='IdentityVerification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('provider', models.CharField(choices=[('manual', 'Manual Review'), ('mock', 'Prototype Mock API'), ('third_party', 'Third Party API')], default='manual', max_length=30)),
                ('status', models.CharField(choices=[('not_started', 'Not Started'), ('pending', 'Pending'), ('verified', 'Verified'), ('rejected', 'Rejected')], default='not_started', max_length=30)),
                ('id_last4', models.CharField(blank=True, max_length=4)),
                ('verified_full_name', models.CharField(blank=True, max_length=150)),
                ('id_document', models.ImageField(blank=True, null=True, upload_to='identity/documents/')),
                ('provider_reference', models.CharField(blank=True, max_length=120)),
                ('admin_notes', models.TextField(blank=True)),
                ('verified_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Seat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('section', models.CharField(max_length=20)),
                ('row', models.CharField(max_length=20)),
                ('number', models.CharField(max_length=20)),
                ('view_quality', models.CharField(choices=[('excellent', 'Excellent'), ('good', 'Good'), ('limited', 'Limited')], default='good', max_length=20)),
                ('is_shaded', models.BooleanField(default=False)),
                ('sun_exposure', models.CharField(choices=[('low', 'Low'), ('medium', 'Medium'), ('high', 'High')], default='medium', max_length=20)),
                ('notes', models.CharField(blank=True, max_length=255)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'ordering': ['section', 'row', 'number'],
            },
        ),
        migrations.CreateModel(
            name='SeatCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=80)),
                ('description', models.TextField(blank=True)),
                ('base_price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('benefits', models.TextField(blank=True)),
            ],
        ),
        migrations.AlterUniqueTogether(
            name='ticket',
            unique_together=set(),
        ),
        migrations.RemoveField(
            model_name='booking',
            name='tickets_count',
        ),
        migrations.RemoveField(
            model_name='parkingreservation',
            name='booking',
        ),
        migrations.AddField(
            model_name='booking',
            name='expires_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='booking',
            name='identity_checked',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='parkingreservation',
            name='ticket',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='parking_reservations', to='booking.ticket'),
        ),
        migrations.AlterField(
            model_name='ticket',
            name='booking',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='ticket', to='booking.booking'),
        ),
        migrations.AddConstraint(
            model_name='parkingreservation',
            constraint=models.UniqueConstraint(condition=models.Q(('status', 'active')), fields=('user', 'match'), name='unique_active_parking_per_user_match'),
        ),
        migrations.AddField(
            model_name='identityverification',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='identity_verification', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='seat',
            name='gate',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='seats', to='stadium.gate'),
        ),
        migrations.AddField(
            model_name='seat',
            name='stadium',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='seats', to='stadium.stadium'),
        ),
        migrations.AddField(
            model_name='booking',
            name='seat',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='bookings', to='booking.seat'),
        ),
        migrations.AddField(
            model_name='ticket',
            name='seat',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, related_name='tickets', to='booking.seat'),
            preserve_default=False,
        ),
        migrations.AddConstraint(
            model_name='booking',
            constraint=models.UniqueConstraint(condition=models.Q(('status__in', ['pending', 'confirmed'])), fields=('user', 'match'), name='unique_active_booking_per_user_match'),
        ),
        migrations.AddConstraint(
            model_name='ticket',
            constraint=models.UniqueConstraint(condition=models.Q(('status__in', ['active', 'used'])), fields=('match', 'seat'), name='unique_active_ticket_per_match_seat'),
        ),
        migrations.AddConstraint(
            model_name='ticket',
            constraint=models.UniqueConstraint(condition=models.Q(('status', 'active')), fields=('user', 'match'), name='unique_active_ticket_per_user_match'),
        ),
        migrations.AddField(
            model_name='seat',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='seats', to='booking.seatcategory'),
        ),
        migrations.RemoveField(
            model_name='ticket',
            name='seat_number',
        ),
        migrations.AddConstraint(
            model_name='seat',
            constraint=models.UniqueConstraint(fields=('stadium', 'section', 'row', 'number'), name='unique_seat_per_stadium'),
        ),
    ]
