# Generated by Django 6.0.4 on 2026-05-04 16:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0002_identityverification_seat_seatcategory_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking',
            name='status',
            field=models.CharField(choices=[('pending_payment', 'Pending Payment'), ('paid', 'Paid'), ('confirmed', 'Confirmed'), ('cancelled', 'Cancelled'), ('expired', 'Expired')], default='pending_payment', max_length=20),
        ),
    ]
