# Generated by Django 6.0.4 on 2026-05-05 02:04

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0003_alter_booking_status'),
        ('match', '0003_match_video_file_alter_match_video_url'),
        ('stadium', '0003_alter_facility_options_gate_crowd_percentage_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='ticket',
            name='unique_active_ticket_per_match_seat',
        ),
        migrations.AddField(
            model_name='identityverification',
            name='id_hash',
            field=models.CharField(blank=True, db_index=True, max_length=64),
        ),
        migrations.AddField(
            model_name='ticket',
            name='used_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='ticket',
            name='gate',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tickets', to='stadium.gate'),
        ),
        migrations.AlterField(
            model_name='ticket',
            name='ticket_code',
            field=models.CharField(blank=True, max_length=40, unique=True),
        ),
        migrations.AddConstraint(
            model_name='ticket',
            constraint=models.UniqueConstraint(condition=models.Q(('status__in', ['active', 'used'])), fields=('match', 'seat'), name='unique_active_or_used_ticket_per_match_seat'),
        ),
    ]
