# Generated by Django 6.0.4 on 2026-05-05 03:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0004_remove_ticket_unique_active_ticket_per_match_seat_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='TicketHolder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=150)),
                ('holder_type', models.CharField(choices=[('mr', 'Mr'), ('ms', 'Ms'), ('child', 'Child')], max_length=20)),
                ('date_of_birth', models.DateField()),
                ('id_last4', models.CharField(max_length=4)),
                ('id_hash', models.CharField(db_index=True, max_length=64)),
                ('id_document', models.ImageField(blank=True, null=True, upload_to='identity/documents/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.RemoveConstraint(
            model_name='booking',
            name='unique_active_booking_per_user_match',
        ),
        migrations.RemoveConstraint(
            model_name='ticket',
            name='unique_active_ticket_per_user_match',
        ),
        migrations.AlterField(
            model_name='ticket',
            name='booking',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ticket', to='booking.booking'),
        ),
        migrations.AddField(
            model_name='ticket',
            name='holder',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='tickets', to='booking.ticketholder'),
        ),
        migrations.RemoveField(
            model_name='booking',
            name='seat',
        ),
    ]
