# Generated by Django 6.0.4 on 2026-05-05 19:04

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0007_booking_parking_area_booking_parking_gate_and_more'),
        ('match', '0003_match_video_file_alter_match_video_url'),
        ('stadium', '0003_alter_facility_options_gate_crowd_percentage_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='booking',
            name='parking_area',
        ),
        migrations.RemoveField(
            model_name='booking',
            name='parking_gate',
        ),
        migrations.RemoveField(
            model_name='booking',
            name='parking_paid',
        ),
        migrations.RemoveField(
            model_name='booking',
            name='parking_price',
        ),
        migrations.RemoveField(
            model_name='booking',
            name='parking_type',
        ),
        migrations.AddField(
            model_name='parkingreservation',
            name='paid',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='parkingreservation',
            name='price',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AlterField(
            model_name='parkingreservation',
            name='match',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='parking_reservations', to='match.match'),
        ),
        migrations.AlterField(
            model_name='parkingreservation',
            name='parking',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reservations', to='stadium.parking'),
        ),
        migrations.AlterField(
            model_name='parkingreservation',
            name='stadium',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='parking_reservations', to='stadium.stadium'),
        ),
        migrations.AlterField(
            model_name='parkingreservation',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('active', 'Active'), ('cancelled', 'Cancelled')], default='pending', max_length=20),
        ),
        migrations.AlterField(
            model_name='parkingreservation',
            name='ticket',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='parking_reservation', to='booking.ticket'),
        ),
        migrations.AlterField(
            model_name='parkingreservation',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='parking_reservations', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddConstraint(
            model_name='parkingreservation',
            constraint=models.UniqueConstraint(condition=models.Q(('status__in', ['pending', 'active'])), fields=('ticket',), name='unique_parking_per_active_ticket'),
        ),
    ]
