# Generated by Django 6.0.4 on 2026-05-05 20:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0008_remove_booking_parking_area_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='parkingreservation',
            name='parking',
        ),
    ]
