# Generated by Django 6.0.4 on 2026-05-01 02:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('stadium', '0002_alter_stadium_options_alter_stadium_unique_together_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Service',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('service_type', models.CharField(max_length=100)),
                ('location', models.CharField(max_length=200)),
                ('status', models.CharField(max_length=20)),
                ('description', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('stadium', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='services', to='stadium.stadium')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('location', models.CharField(max_length=200)),
                ('start_datetime', models.DateTimeField()),
                ('end_datetime', models.DateTimeField()),
                ('city', models.CharField(max_length=100)),
                ('status', models.CharField(max_length=20)),
                ('image', models.ImageField(blank=True, null=True, upload_to='events/')),
                ('video_url', models.URLField(blank=True, null=True)),
                ('stadium', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='events', to='stadium.stadium')),
                ('services', models.ManyToManyField(related_name='events', to='service.service')),
            ],
            options={
                'ordering': ['-start_datetime'],
            },
        ),
    ]
