# Generated by Django 6.0.4 on 2026-05-01 09:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('service', '0002_servicecategory_alter_event_options_and_more'),
        ('stadium', '0002_alter_stadium_options_alter_stadium_unique_together_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='service',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='services', to='service.servicecategory'),
        ),
        migrations.AlterField(
            model_name='service',
            name='delivery_apps',
            field=models.JSONField(blank=True, help_text="Example: ['Jahez', 'HungerStation']", null=True),
        ),
        migrations.AlterField(
            model_name='service',
            name='distance',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='servicecategory',
            name='name',
            field=models.CharField(max_length=100, unique=True),
        ),
        migrations.AddIndex(
            model_name='service',
            index=models.Index(fields=['category'], name='service_ser_categor_e70e5d_idx'),
        ),
        migrations.AddIndex(
            model_name='service',
            index=models.Index(fields=['status'], name='service_ser_status_6c8f27_idx'),
        ),
    ]
