# Generated by Django 6.0.4 on 2026-05-01 09:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('match', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='match',
            options={'ordering': ['-start_datetime']},
        ),
        migrations.AlterModelOptions(
            name='player',
            options={'ordering': ['team', 'number']},
        ),
        migrations.AlterModelOptions(
            name='team',
            options={'ordering': ['name']},
        ),
        migrations.AlterUniqueTogether(
            name='player',
            unique_together={('team', 'number')},
        ),
    ]
