# Generated by Django 6.0.4 on 2026-05-04 13:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('match', '0002_alter_match_options_alter_player_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='match',
            name='video_file',
            field=models.FileField(blank=True, null=True, upload_to='matches/videos/'),
        ),
        migrations.AlterField(
            model_name='match',
            name='video_url',
            field=models.URLField(blank=True, null=True),
        ),
    ]
