# Generated by Django 6.0.4 on 2026-05-06 08:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('match', '0003_match_video_file_alter_match_video_url'),
    ]

    operations = [
        migrations.AlterField(
            model_name='match',
            name='available_tickets',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='match',
            name='total_tickets',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
